"""Core types, exceptions, validators, and utilities for magma-multigas."""

from .exceptions import (
    CacheError,
    ColumnError,
    ConfigError,
    DatasetError,
    DateRangeError,
    FilterError,
    LoaderError,
    MagmaMultigasError,
    MetadataError,
    PlotError,
    ValidationError,
)
from .types import (
    CacheMetadataDict,
    ColumnName,
    Comparator,
    DatasetMetadataDict,
    DatasetType,
    DateLike,
    FileFormat,
    LogLevel,
    PathLike,
    PlotConfigDict,
)
from .utilities import (
    all_evaluations,
    convert_to_direction,
    convert_to_quadrant,
    get_slope_and_intercept,
    mean_squared_error,
    r_squared,
    regression_function,
    root_mean_squared_error,
    y_prediction,
)
from .validators import (
    COMPARATORS,
    STATUS_DESCRIPTION,
    STATUS_NO,
    STATUSES,
    TYPE_OF_DATA,
    in_values,
    validate_column_name,
    validate_comparator,
    validate_date,
    validate_datetime,
    validate_file_type,
    validate_index_as_datetime,
    validate_multigas_data_type,
    validate_selected_data,
    validate_status,
)

__all__ = [
    # Types
    "DatasetType",
    "LogLevel",
    "FileFormat",
    "DateLike",
    "ColumnName",
    "Comparator",
    "PathLike",
    "DatasetMetadataDict",
    "CacheMetadataDict",
    "PlotConfigDict",
    # Exceptions
    "MagmaMultigasError",
    "DatasetError",
    "ValidationError",
    "CacheError",
    "LoaderError",
    "MetadataError",
    "FilterError",
    "ColumnError",
    "DateRangeError",
    "PlotError",
    "ConfigError",
    # Validators
    "STATUSES",
    "STATUS_NO",
    "STATUS_DESCRIPTION",
    "COMPARATORS",
    "TYPE_OF_DATA",
    "validate_file_type",
    "validate_selected_data",
    "validate_comparator",
    "in_values",
    "validate_column_name",
    "validate_status",
    "validate_date",
    "validate_datetime",
    "validate_index_as_datetime",
    "validate_multigas_data_type",
    # Utilities
    "regression_function",
    "get_slope_and_intercept",
    "y_prediction",
    "mean_squared_error",
    "root_mean_squared_error",
    "r_squared",
    "all_evaluations",
    "convert_to_direction",
    "convert_to_quadrant",
]
